# Generated by Django 5.2.1 on 2025-07-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivilegeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('allow_admin', models.BooleanField(default=True)),
                ('allow_nurse', models.BooleanField(default=False)),
            ],
        ),
    ]
